# Generated by Django 4.2.2 on 2023-07-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='player_name',
        ),
    ]
