# Generated by Django 4.2.2 on 2023-07-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_event_notes_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.event'),
        ),
    ]
