# Generated by Django 4.2.2 on 2023-06-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_piece_part_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='part_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Inst3Piece', to='music.part'),
        ),
        migrations.AddField(
            model_name='piece',
            name='part_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Inst4Piece', to='music.part'),
        ),
        migrations.AddField(
            model_name='piece',
            name='part_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Inst5Piece', to='music.part'),
        ),
        migrations.AddField(
            model_name='piece',
            name='part_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Inst6Piece', to='music.part'),
        ),
    ]
