# Generated by Django 4.2.2 on 2023-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_piece_part_3_piece_part_4_piece_part_5_piece_part_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('pieces', models.ManyToManyField(to='music.piece')),
            ],
        ),
    ]
