# Generated by Django 4.2.2 on 2023-07-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_alter_piece_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.instrument'),
        ),
        migrations.AlterField(
            model_name='part',
            name='player',
            field=models.ForeignKey(blank=True, default='Unassigned', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
