# Generated by Django 4.2.2 on 2023-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='music.player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='music.piece'),
        ),
    ]
