# Generated by Django 4.2.2 on 2023-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_part_is_present_part_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
