# Generated by Django 4.2.2 on 2023-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_event_attendees_alter_event_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='part_1',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='part_2',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='part_3',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='part_4',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='part_5',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='part_6',
        ),
        migrations.AddField(
            model_name='part',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='number_of_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='parts',
            field=models.ManyToManyField(blank=True, to='music.part'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
