# Generated by Django 4.2.2 on 2023-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_part_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
