# Generated by Django 4.2.2 on 2023-06-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_piece_part_1_remove_piece_part_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='parts',
        ),
        migrations.AddField(
            model_name='part',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.piece'),
        ),
        migrations.AddField(
            model_name='piece',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.event'),
        ),
    ]
