# Generated by Django 4.2.2 on 2023-06-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_event_pieces_remove_piece_parts_part_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='chosen_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='piece',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='part',
            name='player',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.CASCADE, to='music.player'),
        ),
    ]
