# Generated by Django 4.2.2 on 2023-06-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_piece_chosen_by_piece_notes_alter_part_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='intrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.instrument'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='player',
            field=models.ForeignKey(default='Unassigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='music.player'),
        ),
    ]
