# Generated by Django 4.2.2 on 2023-06-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_part_intrument_alter_part_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='intrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.instrument'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
