# Generated by Django 4.2.2 on 2023-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_part_intrument_alter_part_part_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='intrument',
            new_name='instrument',
        ),
    ]
